services:
  postgres:
    image: postgres:17
    container_name: shopflow-postgres
    environment:
      POSTGRES_DB: shopflow
      POSTGRES_USER: shopflow
      POSTGRES_PASSWORD: shopflow
    ports:
      - "5432:5432"
    volumes:
      - shopflow_pgdata:/var/lib/postgresql/data

volumes:
  shopflow_pgdata:
